const data = {
  cart: [
    {
      id: '1',
      name: 'Smart-Watch HUAWEI Watch GT Classic',
      category: 'men-watch',
      image: 'https://res.cloudinary.com/blackie2020/image/upload/v1617958453/beautiful-eyes-wallpaper_cfbse3.jpg',
      price: 5999,
      countInStock: 10,
      brand: 'Huawei',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    // {
    //   _id: '2',
    //   name: 'Adidas Fit Shirt',
    //   category: 'Shirts',
    //   image: '/images/p2.jpg',
    //   price: 100,
    //   countInStock: 20,
    //   brand: 'Adidas',
    //   rating: 4.0,
    //   numReviews: 12,
    //   description: 'high quality product',
    // },
    // {
    //   _id: '3',
    //   name: 'Lacoste Casual Shirt',
    //   category: 'Shirts',
    //   image: '/images/p3.jpg',
    //   price: 220,
    //   countInStock: 0,
    //   brand: 'Lacoste',
    //   rating: 4.8,
    //   numReviews: 17,
    //   description: 'high quality product',
    // },
    // {
    //   _id: '4',
    //   name: 'Nike Slim Pants',
    //   category: 'Pants',
    //   image: '/images/p4.jpg',
    //   price: 88,
    //   countInStock: 20,
    //   brand: 'Nike',
    //   rating: 4.5,
    //   numReviews: 14,
    //   description: 'high quality product',
    // },
    // {
    //   _id: '5',
    //   name: 'Puma Free Pants',
    //   category: 'Pants',
    //   image: '/images/p5.jpg',
    //   price: 65,
    //   countInStock: 15,
    //   brand: 'Puma',
    //   rating: 4.8,
    //   numReviews: 13,
    //   description: 'high quality product',
    // },
    // {
    //   _id: '6',
    //   name: 'Adidas Fit Pants',
    //   category: 'Pants',
    //   image: '/images/p6.jpg',
    //   price: 135,
    //   countInStock: 12,
    //   brand: 'Adidas',
    //   rating: 4.6,
    //   numReviews: 15,
    //   description: 'high quality product',
    // },
  ],
};
export default data;
