export const ADD_COMMENT = 'ADD_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS';
export const SET_COMMENTS_LOADING = 'SET_COMMENTS_LOADING';
export const GET_CUSTOMER_COMMENTS = 'GET_CUSTOMER_COMMENTS';
export const GET_PRODUCT_COMMENTS = 'GET_PRODUCT_COMMENTS';
