export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const CLEAR_FAVORITES = 'CLEAR_FAVORITES';
export const SET_ISLOADING = 'SET_ISLOADING';
export const LOAD_FAVORITES = 'LOAD_FAVORITES';
