export const FAVORITES_SET_ISLOADING = 'FAVORITES_SET_ISLOADING';
export const FAVORITES_LOAD = 'FAVORITES_LOAD';
export const FAVORITES_ADD_ITEM = 'FAVORITES_ADD_ITEM';
export const FAVORITES_REMOVE_ITEM = 'FAVORITES_REMOVE_ITEM';
export const FAVORITES_CLEAR = 'FAVORITES_CLEAR';
