const sliderData = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: 'https://res.cloudinary.com/blackie2020/image/upload/v1617958453/beautiful-eyes-wallpaper_cfbse3.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image:
        'https://res.cloudinary.com/blackie2020/image/upload/v1617958452/a6f92c28262e05a3fd2264bb2db59e85beautiful-pictures_clcvcn.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Lacoste Free Shirt',
      category: 'Shirts',
      image: 'https://res.cloudinary.com/blackie2020/image/upload/v1617958452/1473462beautiful-pictures_raoztw.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: 'https://res.cloudinary.com/blackie2020/image/upload/v1617958454/beautiful-nature-pictures-7_qn44fx.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Puma Slim Pant',
      category: 'Pants',
      image: 'https://res.cloudinary.com/blackie2020/image/upload/v1617958452/Beautiful-Farm_lkpbkh.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: 'https://res.cloudinary.com/blackie2020/image/upload/v1617958453/Beautiful-HD-Wallpapers-15_c34dr7.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default sliderData;
