export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_ONE_PRODUCT = 'SET_ONE_PRODUCT';
export const SET_PRODUCTS_LOADING = 'SET_PRODUCTS_LOADING';
export const SET_ONE_PRODUCT_LOADING = 'SET_ONE_PRODUCT_LOADING';
